# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vouchers_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField()),
                ('deal_id', models.CharField(max_length=10)),
                ('voucher_id', models.CharField(max_length=10)),
            ],
        ),
    ]
