# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_class',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
