# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_image_class_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
                ('deal_category', models.IntegerField()),
                ('deal_type', models.IntegerField()),
                ('store_name', models.CharField(max_length=100)),
                ('store_location', models.CharField(max_length=100)),
                ('store_address', models.CharField(max_length=2000)),
                ('store_phone', models.BigIntegerField()),
                ('store_latitude', models.CharField(max_length=10)),
                ('store_longitude', models.CharField(max_length=10)),
                ('deal_heading', models.CharField(max_length=2000)),
                ('deal_description', models.CharField(max_length=2000)),
                ('deal_validity', models.DateField(null=True)),
                ('deal_activate', models.CharField(max_length=2000)),
                ('weightage', models.IntegerField()),
                ('deal_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='image_class',
        ),
    ]
