# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20161003_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='_class',
            new_name='deals',
        ),
    ]
