# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20161004_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='deal_validity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
