# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20161006_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='deal_activate',
            field=models.TextField(),
        ),
    ]
