# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20161006_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='text',
        ),
        migrations.AddField(
            model_name='notif',
            name='texts',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts_db',
            name='contact_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deals',
            name='deal_activate',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='deals',
            name='deal_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deals',
            name='deal_heading',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deals',
            name='store_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notif',
            name='heading',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notif',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
