# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20161013_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notif',
            old_name='texts',
            new_name='textz',
        ),
    ]
