# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20161013_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='textz',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
