# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20161013_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='heading',
            field=models.CharField(max_length=1000),
        ),
    ]
