# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_auto_20161020_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notif',
            new_name='notifications',
        ),
    ]
