# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_proc', '0003_auto_20161004_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_db',
            name='profile_id',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
