# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_proc', '0004_signup_db_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_db',
            name='no_of_refs',
            field=models.IntegerField(default=0),
        ),
    ]
