# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_proc', '0005_signup_db_no_of_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_db',
            name='fpass',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='signup_db',
            name='gcmid',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='signup_db',
            name='otp_ver',
            field=models.IntegerField(default=0),
        ),
    ]
